name: Upload TICKIT data to S3

on:
  workflow_dispatch:

jobs:
  upload_s3_data:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install AWS CLI
        run: |
          pip install awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::102606406933:role/github-action-role

      - name: Move data
        run: |
          sudo apt-get install -y unzip
          cd data
          unzip tickit_data.zip
          rm tickit_data.zip
          aws s3 cp . s3://mkis-redshift-app-eu-central-1/raw_data --recursive

      - name: Move scripts
        run: |
          cd etl
          aws s3 cp . s3://mkis-redshift-app-eu-central-1/etl --recursive

